export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
    'SEND' : 'Enviar',
    'LOGIN'  : 'Acceder',
    'LOGOUT' : 'Desconectarse',
    'EDIT' : 'Editar',
    'SAVE' : 'Guardar',
    'CANCEL' : 'Cancelar',
    'REMOVE' : 'Eliminar',
    'ENTER_YOUR_EMAIL' : 'Escribe tu email',
    'ENTER_YOUR_PASSWORD' : 'Escribe tu contraseña',
    'CREATE_AN_ACCOUNT' : 'Crea una cuenta',
    'SIGN_IN' : 'Registrarse',
    'ALL_FIELDS_IS_REQUIRED' : 'Todos los campos son obligatorios',
    'ENTER_YOUR_FULLNAME': 'Introduce tu nombre completo',
    'ENTER_YOUR_ADDRESS': 'Introduce tu dirección',
    'ENTER_YOUR_CITY': 'Introduce tu ciudad',
    'SELECT_YOUR_COUNTRY' : 'Selecciona tu país',
    'RETYPE_YOUR_PASSWORD' : 'Reintroduce tu contraseña',
    'BACK': 'Volver',
    'FORGET_PASSWORD' : '¿Olvidaste tu contraseña?',
    'ENTER_YOUR_EMAIL_TO_RESET_PASSWORD' : 'Introduce tu email para resetear tu contraseña',
    'THIS_FIELD_IS_REQUIRED' : 'Este campo es obligatorio',
    'THIS_EMAIL_IS_INVALID' : 'El email escrito es inválido',
    'PASSWORD_DOES_NOT_MATCH' : 'Las contraseñas no coinciden',
    'ENTER_YOUR_EMAIL_RESET_PASSWORD' : 'Introduzca su dirección de correo electrónico para restablecer la contraseña',
    'APPLICATIONS' : 'Aplicaciones',
    'APPLICATION' : 'Aplicación',
    'NEW_APPLICATION' : 'Nueva Aplicación',
    'SELECT_A_PICTURE' : 'Selecciona una imagen',
    'YOU_HAVE_NOT_CREATED_YET_ANY' : 'No has creado aún ninguna',
    'MAKE_YOUR_FIRST_APPLICATION_TO_START' : 'Haz tu primera aplicación para empezar',
    'PLATFORMS' : 'Plataformas',
    'DOMAIN' : 'Dominio',
    'APPLICATION_NAME' : 'Nombre de la Aplicación',
    'APPLICATION_CODE' : 'Código de la Aplicación',
    'ICON' : 'Icono',
    'PAGES' : 'Páginas',
    'PAGE' : 'Página',
    'NEW_PAGE' : 'Nueva Página',
    'MAKE_YOUR_FIRST_PAGE_TO_START' : 'Haz tu primera página para empezar',
    'PAGE_NAME' : 'Nombre de la página',
    'PAGE_SLUG' : 'Slug de la página',
    'PAGE_ACTIVE' : 'Activar página',
    'ENTER_PAGE_TITLE' : 'Escribe el título de la página',
    'ENTER_PAGE_DESCRIPTION' : 'Enter la descripción de la página',
    'ENTER_PAGE_KEYWORDS' : 'Enter las palabras clave (entre comas)',
    'TITLE' : 'Título',
    'SEO_CONTENT' : 'Contenido SEO',
    'DESCRIPTION' : 'Descripción',
    'ENTER_NAME' : 'Introduce un nombre',
    'THIS_CODE_IS_INVALID' : 'Este código no es válido',
    'THIS_DOMAIN_IS_INVALID' : 'Este dominio no es válido',
    'LANGUAGES' : 'Idiomas',
    'NEW_WIDGET' : 'Nuevo Widget',
    'COMPONENTS' : 'Componentes',
    'CREATED_AT' : 'Creada',
    'ENGLISH' : 'Inglés',
    'SPANISH' : 'Español',
    'USER_NOT_EXIST' : 'El usuario no existe',
    'PROFILE' : 'Perfil'
};
