export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'SEND': 'Send',
    'LOGIN': 'Login',
    'LOGOUT': 'Logout',
    'EDIT': 'Edit',
    'SAVE': 'Guardar',
    'CANCEL': 'Cancelar',
    'REMOVE': 'Remove',
    'ENTER_YOUR_EMAIL': 'Enter your email',
    'ENTER_YOUR_PASSWORD': 'Enter your password',
    'CREATE_AN_ACCOUNT': 'Create an account',
    'SIGN_IN': 'Sign in',
    'ALL_FIELDS_IS_REQUIRED': 'All fields is required',
    'ENTER_YOUR_FULLNAME': 'Enter your fullname',
    'ENTER_YOUR_ADDRESS': 'Enter your address',
    'ENTER_YOUR_CITY': 'Enter your city',
    'SELECT_YOUR_COUNTRY': 'Select your country',
    'RETYPE_YOUR_PASSWORD': 'Re-type your password',
    'BACK': 'Back',
    'FORGET_PASSWORD': 'Forget Password?',
    'ENTER_YOUR_EMAIL_TO_RESET_PASSWORD': 'Enter your e-mail address below to reset your password.',
    'THIS_FIELD_IS_REQUIRED': 'This field is required',
    'THIS_EMAIL_IS_INVALID': 'This email is invalid',
    'PASSWORD_DOES_NOT_MATCH': 'Password does not match',
    'APPLICATIONS': 'Applications',
    'APPLICATION': 'Application',
    'NEW_APPLICATION': 'New Application',
    'SELECT_A_PICTURE': 'Select a picture',
    'YOU_HAVE_NOT_CREATED_YET_ANY': 'You have not created yet any',
    'MAKE_YOUR_FIRST_APPLICATION_TO_START': 'Make your first application to start',
    'PLATFORMS': 'Platforms',
    'DOMAIN': 'Domain',
    'APPLICATION_NAME': 'Application Name',
    'APPLICATION_CODE': 'Application Code',
    'ICON': 'Icon',
    'PAGES': 'Pages',
    'PAGE': 'Page',
    'NEW_PAGE': 'New Page',
    'MAKE_YOUR_FIRST_PAGE_TO_START': 'Make your fist page to start',
    'PAGE_NAME': 'Page Name',
    'PAGE_SLUG': 'Page Slug',
    'PAGE_ACTIVE': 'Page Active',
    'ENTER_PAGE_TITLE': 'Enter Page Title',
    'ENTER_PAGE_DESCRIPTION': 'Enter Page Descrition',
    'ENTER_PAGE_KEYWORDS': 'Enter Page Keywords (with commas)',
    'TITLE': 'Title',
    'SEO_CONTENT': 'SEO Content',
    'DESCRIPTION': 'Description',
    'ENTER_NAME': 'Enter name',
    'THIS_CODE_IS_INVALID': 'This code is invalid',
    'THIS_DOMAIN_IS_INVALID': 'This domian is invalid',
    'LANGUAGES': 'Languages',
    'NEW_WIDGET': 'New Widget',
    'COMPONENTS': 'Components',
    'CREATED_AT': 'Created at',
    'ENGLISH': 'English',
    'SPANISH': 'Spanish'
};
